# Generated by Django 2.2.7 on 2020-01-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='label',
            field=models.CharField(default='No level', max_length=55),
        ),
        migrations.AddField(
            model_name='status',
            name='label',
            field=models.CharField(default='No Status', max_length=55),
        ),
    ]
