# Generated by Django 2.2.7 on 2020-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200120_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='label',
            field=models.CharField(default='No description', max_length=255),
        ),
    ]
