# Generated by Django 2.2.7 on 2020-01-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ticket_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
