# Generated by Django 2.2.7 on 2020-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_client',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_dev',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ManyToManyField(to='app.Company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
