# Generated by Django 2.2.7 on 2020-01-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200120_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='label',
            field=models.TextField(default='No description', max_length=255),
        ),
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_client', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='companyProject',
            field=models.ManyToManyField(through='app.CompanyProject', to='app.Project'),
        ),
    ]
