# Generated by Django 2.2.7 on 2020-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200120_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyProject',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ManyToManyField(through='app.CompanyProject', to='app.Company'),
        ),
    ]
