# Generated by Django 2.2.7 on 2020-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200120_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ManyToManyField(related_name='projects', through='app.CompanyProject', to='app.Company'),
        ),
        migrations.DeleteModel(
            name='TicketUser',
        ),
    ]
