# Generated by Django 2.2.7 on 2020-01-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200121_0954'),
        ('app', '0014_auto_20200121_1035'),
    ]

    operations = [
    ]
