# Generated by Django 2.2.7 on 2020-01-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20200121_1547'),
        ('app', '0015_merge_20200122_0823'),
    ]

    operations = [
    ]
