# Generated by Django 2.2.7 on 2020-01-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20200122_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
