# Generated by Django 2.2.7 on 2020-01-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_role'),
        ('app', '0017_auto_20200122_1517'),
    ]

    operations = [
    ]
